---
title: "GO Enrichments of genes highly correlated to phenotype"
author: "Carson Stacy"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(readr)
library(topGO)
library(biomaRt)
```

# read in gene correlations with slope of recovery scores.
```{r}
cor_traj_genes <- read_table("~/Documents/GitHub/CanarySeq/GOanalysis/cor.traj.genes.csv")

# filter for genes that negatively correlate and get those genes' names
neg_cor_traj_genes <- cor_traj_genes %>%
  filter(r < -0.6) %>%
  pull(gene)

pos_cor_traj_genes <- cor_traj_genes %>%
  filter(r > 0.6) %>%
  pull(gene)
```


```{r}
# get biomart ensembl dataset for scanaria (has most GO terms)
load(file = paste( "~/Documents/GitHub/CanarySeq/geneAnnotations/canary_geneID2GO_BM_MGpost0.RData", sep= ""))
```


```{r}

all_genes_neg <- factor(as.integer(toupper(readr::read_csv("~/Desktop/canary/contrasts/MGpost0.csv")[[1]]) %in% neg_cor_traj_genes)) # create 0 1 factors.

names(all_genes_neg) <- toupper(readr::read_csv("~/Desktop/canary/contrasts/MGpost0.csv")[[1]]) # add gene names
    
all_genes_pos <- factor(as.integer(toupper(readr::read_csv("~/Desktop/canary/contrasts/MGpost0.csv")[[1]]) %in% pos_cor_traj_genes)) # create 0 1 factors.

names(all_genes_pos) <- toupper(readr::read_csv("~/Desktop/canary/contrasts/MGpost0.csv")[[1]]) # add gene names
    
    
GOdata=new('topGOdata', 
           ontology='BP', # 'BP' = Biological Process. Also tried 'ALL' but doesn't work.
           allGenes = all_genes_neg, # all 10188 genes that are in MGpost0 data from edgeR. factor=1 for those that are DE.
           annot = annFUN.gene2GO, # annotation function for custom annotation
           # gene2GO = canary_geneID2GO_BM # annotation db from eggNOG output.
# I am thinking about switching this for one filtered to just edgeR genes:
           gene2GO = canary_geneID2GO_BM # annotation db from BiomaRt.
           # gene2GO = canary_geneID2GO_BM_DE#, 
           # geneSel = DE_genes
           )
```




```{r}

weight_fisher_result <- 
  runTest(GOdata, algorithm='weight01', statistic='fisher') 

allGO <- usedGO(GOdata)

all_res <-
  GenTable(GOdata, weightFisher=weight_fisher_result, orderBy='weightFisher', topNodes=length(allGO), numChar = 200)

p.adj <- round(p.adjust(all_res$weightFisher,method="BH"),digits = 4)

all_res_final=cbind(all_res,p.adj)
all_res_final=all_res_final[order(all_res_final$p.adj),] %>%
      mutate(across(everything(), gsub, pattern = ",", replacement = ";"))

results.table.p= all_res_final[which(as.numeric(all_res_final$weightFisher)<=0.1),] %>%
      mutate(across(everything(), gsub, pattern = ",", replacement = ";"))

#get list of significant GO after multiple testing correction
results.table.bh=all_res_final[which(all_res_final$p.adj<=0.1),] %>%
      mutate(across(everything(), gsub, pattern = ",", replacement = ";"))
```

Quick visualizaiton of correlation of these neg_cor_traj genes with traj values.
```{r}

genPhen_dat_t.tmp14_traj_DE_FC %>% 
  dplyr::slice(-1) %>%
  # add_column(Diet = "protein") %>%
  add_column(Diet = c("lipid","lipid","protein","lipid",
  "lipid","lipid","protein","protein","protein",
  "protein","lipid","lipid","protein","lipid","protein",
  "lipid","protein","lipid")) %>%
  hablar::retype() %>%
  mutate(bird = gene) %>%
  dplyr::select(-gene) %>%
  pivot_longer(!c(bird, Diet, eye_score), names_to = "gene_name", values_to = "fold_change") %>%
  filter(gene_name %in% neg_cor_traj_genes) %>%
  ggplot(aes(x=eye_score, y = fold_change)) +
  geom_point(aes(color = Diet)) +
  geom_smooth(method="lm", color = "black", alpha = 0.7) +
  ggtitle("Correlation between L2FC and eye_score recovery slope MGpost0") +
  labs(x = "slope of eye recovery regression",
       y = "log2FC (day 14 vs day 0)") +
  facet_wrap(~gene_name, scales = "free_y") +
  ggpubr::stat_cor(label.y = -0.5)+
  theme_minimal()
# 
# ggpubr::ggscatterhist(x = "eye_score",
#                   y = "fold_change",
#                   alpha = 0.7,
#                   color = "gene_name",
#                   shape = "Diet",
#                   margin.plot = "density",
#                   bins = 7,
#                   title = paste("Correlation between L2FC and eye_score recovery slope MGpost0", sep = ""),
#                   xlab = "slope of eye recovery regression"
#                   ) #+ 
  # facet_wrap(~gene_name)
```

