---
title: "Tidy_tpm"
author: "Carson Stacy"
date: "2022-10-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
tmp2 <- 
```

Goal of this notebook is to create a tidy dataset of individual gene counts.
```{r}
g.tpm.l <- read.delim("~/Documents/GitHub/CanarySeq/globinModifiedGTFResults/rsem.merged.gene_tpm.tsv", 
                                          header=TRUE)
row.names(g.tpm.l) <- g.tpm.l$gene_id

g.tpm.l$ES89_Blue.049_Control.protein_0 <- NULL #remove the bad sample

############ make the metadata table ######################
meta <- data.frame(SampID = colnames(g.tpm.l[,c(3:106)]))
meta <- meta %>% separate(SampID, 
                          c("Sample.ID", "Bird.ID",
                            "MG.Diet", "Day"), "_", 
                          extra = "warn", fill = "warn", 
                          remove = FALSE) 
View(meta)

meta <- meta %>% separate(MG.Diet, 
                          c("MG.Status", "Diet"), 
                          sep = "[.]", extra = "warn", 
                          fill = "warn", 
                          remove = FALSE) 

meta$MG.Diet.Day <- paste0(meta$MG.Diet, ".", meta$Day)
meta$MG.Day <- paste0(meta$MG.Status, ".", meta$Day)
meta$Diet.Day <- paste0(meta$Diet, ".", meta$Day)

meta <- meta %>% mutate(MG.active = if_else(Day < 1, "NO", 
                                            if_else(MG.Status == "Control",
                                                    "NO", "YES")))
meta$Exposure.MG <- paste0(meta$MG.active, ".", meta$MG.Status)
meta$Exposure.Diet <- paste0(meta$MG.active, ".", meta$Diet)

# View(meta)
row.names(meta) <- (meta$SampID)

g.tpm.l_t <- t(g.tpm.l)
tpm <- g.tpm.l_t[-c(1,2),]
```

# combine the data
```{r}
dat <- cbind(meta, tpm)
rm(g.tpm.l, g.tpm.l_t, meta, tpm)
```

# Make it tidy
```{r}
dat_tidy <- dat %>% 
  pivot_longer(A1CF:ZZZ3, 
               names_to = "gene",
               values_to = "tpm")
rm(dat)
```

```{r}
# some cool genes w/ significant GO terms in Diet0 contrast 
GO0007015 <- c("ARHGAP18" , "CLRN1" ,"CTTN" ,"LIMA1" , "LOC103816370",
               "MKKS" , "RHPN2")    

GO0002250 <- c( "BACH2",   "CD28",    "MLH1"  ,  "THOC1" ,  "ZC3H12A")
```

```{r}
dat_tidy %>%
  filter(Day == 0, gene %in% c(GO0002250, GO0007015)) %>%
  mutate(Sample.ID = fct_reorder(as.factor(Sample.ID), as.integer(as.factor(Diet)))) %>%
  ggplot(aes(x = Sample.ID, y = as.numeric(tpm), fill = Diet)) +
  geom_bar(stat = "identity") +
  facet_wrap(~gene) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

# now let's look at a GO term enriched across interesting contrasts.
```{r}
tmp <- genesInTerm(GOdata_up, "GO:0006955")[[1]] # immune response
tmp <- genesInTerm(GOdata_up, "GO:0006954")[[1]] # inflammatory response
tmp <- genesInTerm(GOdata_up, "GO:0006952")[[1]] # defense response
tmp <- genesInTerm(GOdata_up, "GO:0002250")[[1]] # adaptive immune response
tmp <- genesInTerm(GOdata_up, "GO:0015074")[[1]] # DNA integration
tmp <- genesInTerm(GOdata_up, "GO:0090502")[[1]] # RNA phosphodiester bond hydrolysis; endonucleolytic

trans <- genesInTerm(GOdata_up, "GO:0006412")[[1]] # translation


dat_tidy %>%
  filter(Day == 0, gene %in% tmp[1:100]) %>%
  mutate(Sample.ID = fct_reorder(as.factor(Sample.ID), as.integer(as.factor(Diet)))) %>%
  ggplot(aes(x = Sample.ID, y = as.numeric(tpm), fill = Diet)) +
  geom_bar(stat = "identity") +
  # facet_wrap(~gene) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

dat_tidy %>%
  filter(gene %in% tmp) %>%
  mutate(Sample.ID = fct_reorder(as.factor(Sample.ID), as.integer(as.factor(Diet)))) %>%
  ggplot(aes(x = Sample.ID, y = as.numeric(tpm), fill = Diet)) +
  geom_bar(stat = "identity") +
  facet_wrap(~Day) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

dat_tidy %>%
  filter(gene %in% tmp, as.numeric(tpm) > 1 ) %>%
  ggplot(aes(x = as.numeric(Day), y = as.numeric(tpm), color = Diet)) +
  geom_line(aes( group = interaction(Bird.ID, gene))) +
  geom_smooth(method = "lm", color = "black") +
  theme_classic() +
  facet_wrap(~Diet) +
  scale_y_log10()
```


```{r}

dat_tidy %>%
  filter(Day == 0, gene %in% trans[1:100]) %>%
  mutate(Sample.ID = fct_reorder(as.factor(Sample.ID), as.integer(as.factor(Diet)))) %>%
  ggplot(aes(x = Sample.ID, y = as.numeric(tpm), fill = Diet)) +
  geom_bar(stat = "identity") +
  # facet_wrap(~gene) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

dat_tidy %>%
  filter(gene %in% trans) %>%
  mutate(Sample.ID = fct_reorder(as.factor(Bird.ID), as.integer(as.factor(Diet)))) %>%
  ggplot(aes(x = Bird.ID, y = as.numeric(tpm), fill = Diet)) +
  geom_bar(stat = "identity") +
  facet_wrap(~Day) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

dat_tidy %>%
  filter(gene %in% tmp) %>%
  ggplot(aes(x = as.numeric(Day), y = log2(as.numeric(tpm)), color = MG.Diet)) +
  geom_line(aes( group = interaction(Bird.ID, gene)), size = 1) +
  # geom_smooth(method = "loess", color = "black") +
  theme_classic() +
  # scale_y_log10() +
  facet_wrap(~gene) 

dat_tidy %>%
  filter(gene %in% "MLH1") %>%
  ggplot(aes(x = as.numeric(Day), y = as.numeric(tpm), color = MG.Diet)) +
  geom_line(aes( group = interaction(Bird.ID, gene)), size = 1) +
  # geom_smooth(method = "loess", color = "black") +
  theme_classic() +
  # scale_y_log10() +
  facet_wrap(~MG.Diet) 
```


```{r DE in t0}
tmp0 <- genesInTerm(GOdata_up, "GO:0006955")[[1]] # immune response
tmp0 <- genesInTerm(GOdata_up, "GO:0006954")[[1]] # inflammatory response
tmp0 <- genesInTerm(GOdata_up, "GO:0006952")[[1]] # defense response
tmp0 <- genesInTerm(GOdata_up, "GO:0002250")[[1]] # adaptive immune response
tmp0 <- genesInTerm(GOdata_up, "GO:0015074")[[1]] # DNA integration
```

```{r}

dat_tidy %>%
  filter(gene %in% tmp0[106:205]) %>%
  ggplot(aes(x = as.numeric(Day), y = log2(as.numeric(tpm)), color = MG.Diet)) +
  geom_line(aes( group = interaction(Bird.ID, gene)), size = 1) +
  # geom_smooth(method = "loess", color = "black") +
  theme_classic() +
  # scale_y_log10() +
  facet_wrap(~gene) 

dat_tidy %>%
  filter(gene %in% "LOC103825305") %>%
  ggplot(aes(x = as.numeric(Day), y = log2(as.numeric(tpm)), color = MG.Diet)) +
  geom_line(aes( group = interaction(Bird.ID, gene)), size = 1) +
  # geom_smooth(method = "loess", color = "black") +
  theme_classic() +
  # scale_y_log10() +
  facet_wrap(~Diet) 
```

